/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utfpr.poo2.projectfinal.visao;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import com.utfpr.poo2.projectfinal.rn.FuncionarioRN;
import com.utfpr.poo2.projectfinal.rn.ClienteRN;
import com.utfpr.poo2.projectfinal.rn.CompraRN;
import com.utfpr.poo2.projectfinal.rn.ProdutoRN;

import com.utfpr.poo2.projectfinal.vo.Funcionario;
import com.utfpr.poo2.projectfinal.vo.Cliente;
import com.utfpr.poo2.projectfinal.vo.Compra;
import com.utfpr.poo2.projectfinal.vo.Produto;

/**
 *
 * @author Giuvane Conti
 */
public class CadastrarCompra extends javax.swing.JInternalFrame {

    private Long idAlteracao = 0L;
    private List<Funcionario> funcionarios;
    private FuncionarioRN funcionarioRN;
    private List<Cliente> clientes;
    private ClienteRN clienteRN;
    private List<Produto> produtos;
    private ProdutoRN produtoRN;
    
    private Compra compra;
    private CompraRN compraRN;
    
    public CadastrarCompra() {
        this.funcionarioRN = new FuncionarioRN();
        this.clienteRN = new ClienteRN();
        this.produtoRN = new ProdutoRN();
        this.compraRN = new CompraRN();
        
        initComponents();
        
        this.popularComboFuncionario();
        this.popularComboProduto();
        this.popularComboCliente();
    }
    
    public CadastrarCompra(Long idAlteracao) {
        initComponents();
        this.funcionarioRN = new FuncionarioRN();
        this.clienteRN = new ClienteRN();
        this.produtoRN = new ProdutoRN();
        this.compraRN = new CompraRN();
        this.idAlteracao = idAlteracao;
        try{
            compra = compraRN.listarUm(idAlteracao);
            
            popularComboClienteEdicao(idAlteracao);
            
            popularComboFuncionarioEdicao(idAlteracao);
            
            popularComboProdutoEdicao(idAlteracao);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        comboFuncionario = new javax.swing.JComboBox<>();
        comboProduto = new javax.swing.JComboBox<>();
        comboCliente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Lançamento");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        txtID.setEditable(false);

        jLabel1.setText("ID:");

        jLabel6.setText("Funcionario:");

        jLabel7.setText("Produto:");

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/accept_button.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel_32.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel6, jLabel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        try{
            if(this.idAlteracao == 0){
                compra = new Compra();
                compra.setFuncionario((Funcionario)this.getFuncionarioSelecionada(comboFuncionario.getSelectedIndex()));
                compra.setCliente((Cliente)this.getClienteSelecionado(comboCliente.getSelectedIndex()));
                compra.setProduto((Produto)this.getProdutoSelecionado(comboProduto.getSelectedIndex()));
                
                compraRN.salvar(compra);
                
            }else{
                compra.setFuncionario((Funcionario)this.getFuncionarioSelecionada(comboFuncionario.getSelectedIndex()));
                compra.setCliente((Cliente)this.getClienteSelecionado(comboCliente.getSelectedIndex()));
                compra.setProduto((Produto)this.getProdutoSelecionado(comboProduto.getSelectedIndex()));
                
                compraRN.atualizar(compra);
                
            }
            JOptionPane.showMessageDialog(this, "Compra cadastrado com sucesso!");
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void popularComboFuncionario() {
        ComboBoxModel modeloCat;
            try {
                Vector linhas = new Vector();
                funcionarios = funcionarioRN.listaTodos();
                
                for (Funcionario f : funcionarios)
                {
                    Vector linha = new Vector();
                    linha.add(f.getCodigo());
                    linha.add(f.getNome());
                    linhas.add(linha);
                }
                modeloCat = new DefaultComboBoxModel(linhas);
                comboFuncionario.setModel(modeloCat);
            } catch (Exception e) {

                    e.printStackTrace();
            }
    }
    
    private void popularComboFuncionarioEdicao(Long id) {
        ComboBoxModel modeloCat;
            try {
                Vector linhas = new Vector();
                funcionarios = funcionarioRN.listaTodos();
                int index = 0;
                int indexSelecionado = 0;
                for (Funcionario c : funcionarios)
                {
                    Vector linha = new Vector();
                    linha.add(c.getCodigo());
                    linha.add(c.getNome());
                    linhas.add(linha);
                    
                    if (compra.getFuncionario().getCodigo() == (c.getCodigo())) {
                        indexSelecionado = index;
                    }
                    index++;
                }
                modeloCat = new DefaultComboBoxModel(linhas);
                comboFuncionario.setModel(modeloCat);
                comboFuncionario.setSelectedIndex(indexSelecionado);
            } catch (Exception e) {

                    e.printStackTrace();
            }
    }
    
    private void popularComboCliente() {
        ComboBoxModel modeloCli;
            try {
                Vector linhas = new Vector();
                clientes = clienteRN.listaTodos();
                
                for (Cliente c : clientes)
                {
                    Vector linha = new Vector();
                    linha.add(c.getCodigo());
                    linha.add(c.getNome());
                    linhas.add(linha);
                }
                modeloCli = new DefaultComboBoxModel(linhas);
                comboCliente.setModel(modeloCli);
            } catch (Exception e) {

                    e.printStackTrace();
            }
    }
    
    private void popularComboClienteEdicao(Long id) {
        ComboBoxModel modeloCli;
            try {
                Vector linhas = new Vector();
                clientes = clienteRN.listaTodos();
                int index = 0;
                int indexSelecionado = 0;
                for (Cliente c : clientes)
                {
                    Vector linha = new Vector();
                    linha.add(c.getCodigo());
                    linha.add(c.getNome());
                    linhas.add(linha);
                    
                    if (compra.getCliente().getCodigo() == (c.getCodigo())) {
                        indexSelecionado = index;
                    }
                    index++;
                }
                modeloCli = new DefaultComboBoxModel(linhas);
                comboCliente.setModel(modeloCli);
                comboCliente.setSelectedIndex(indexSelecionado);
            } catch (Exception e) {

                    e.printStackTrace();
            }
    }
    
    private void popularComboProduto() {
        ComboBoxModel modeloCli;
            try {
                Vector linhas = new Vector();
                produtos = produtoRN.listaTodos();
                
                for (Produto c : produtos)
                {
                    Vector linha = new Vector();
                    linha.add(c.getCodigo());
                    linha.add(c.getNome());
                    linhas.add(linha);
                }
                modeloCli = new DefaultComboBoxModel(linhas);
                comboProduto.setModel(modeloCli);
            } catch (Exception e) {

                    e.printStackTrace();
            }
    }
    
    private void popularComboProdutoEdicao(Long id) {
        ComboBoxModel modeloCli;
            try {
                Vector linhas = new Vector();
                produtos = produtoRN.listaTodos();
                int index = 0;
                int indexSelecionado = 0;
                for (Produto c : produtos)
                {
                    Vector linha = new Vector();
                    linha.add(c.getCodigo());
                    linha.add(c.getNome());
                    linhas.add(linha);
                    
                    if (compra.getCliente().getCodigo() == (c.getCodigo())) {
                        indexSelecionado = index;
                    }
                    index++;
                }
                modeloCli = new DefaultComboBoxModel(linhas);
                comboProduto.setModel(modeloCli);
                comboProduto.setSelectedIndex(indexSelecionado);
            } catch (Exception e) {

                    e.printStackTrace();
            }
    }
    
    private Object getFuncionarioSelecionada(int posicao) 
    {
        Funcionario c = new Funcionario();
        c = (Funcionario) funcionarios.get(posicao);

        return c;
    }
    
    private Object getClienteSelecionado(int posicao) 
    {
        Cliente c = new Cliente();
        c = (Cliente) clientes.get(posicao);

        return c;
    }
    
    private Object getProdutoSelecionado(int posicao) 
    {
        Produto c = new Produto();
        c = (Produto) produtos.get(posicao);

        return c;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboFuncionario;
    private javax.swing.JComboBox<String> comboProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
