/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utfpr.poo2.projectfinal.visao;

import javax.persistence.EntityManager;
import com.utfpr.poo2.projectfinal.dao.ConexaoHibernate;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        // Iniciar conexão com base de dados
        EntityManager manager = ConexaoHibernate.getInstance();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        imCadastro = new javax.swing.JMenu();
        imCliente = new javax.swing.JMenuItem();
        imFuncionario = new javax.swing.JMenuItem();
        imFornecedor = new javax.swing.JMenuItem();
        imCargo = new javax.swing.JMenuItem();
        imProduto = new javax.swing.JMenuItem();
        imCompra = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPrincipal.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        imCadastro.setText("Cadastro");

        imCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/client_account_template.png"))); // NOI18N
        imCliente.setText("Cliente");
        imCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imClienteActionPerformed(evt);
            }
        });
        imCadastro.add(imCliente);

        imFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/client_account_template.png"))); // NOI18N
        imFuncionario.setText("Funcionario");
        imFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imFuncionarioActionPerformed(evt);
            }
        });
        imCadastro.add(imFuncionario);

        imFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/client_account_template.png"))); // NOI18N
        imFornecedor.setText("Fornecedor");
        imFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imFornecedorActionPerformed(evt);
            }
        });
        imCadastro.add(imFornecedor);

        imCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/categories.png"))); // NOI18N
        imCargo.setText("Cargo");
        imCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCargoActionPerformed(evt);
            }
        });
        imCadastro.add(imCargo);

        imProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/categories.png"))); // NOI18N
        imProduto.setText("Produto");
        imProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imProdutoActionPerformed(evt);
            }
        });
        imCadastro.add(imProduto);

        imCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/bank.png"))); // NOI18N
        imCompra.setText("Compra");
        imCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCompraActionPerformed(evt);
            }
        });
        imCadastro.add(imCompra);

        jMenuBar1.add(imCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imClienteActionPerformed
        // TODO add your handling code here:
        ConsultarCliente consultaCliente = new ConsultarCliente(jdpPrincipal);
        this.jdpPrincipal.add(consultaCliente);
        consultaCliente.setVisible(true);
    }//GEN-LAST:event_imClienteActionPerformed

    private void imCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCargoActionPerformed
        // TODO add your handling code here:
        ConsultarCargo consultaCargo = new ConsultarCargo(jdpPrincipal);
        this.jdpPrincipal.add(consultaCargo);
        consultaCargo.setVisible(true);
    }//GEN-LAST:event_imCargoActionPerformed

    private void imProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imProdutoActionPerformed
        // TODO add your handling code here:
        ConsultarProduto consultaProduto = new ConsultarProduto(jdpPrincipal);
        this.jdpPrincipal.add(consultaProduto);
        consultaProduto.setVisible(true);
    }//GEN-LAST:event_imProdutoActionPerformed

    private void imFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imFuncionarioActionPerformed
        // TODO add your handling code here:
        ConsultarFuncionario consultaFuncionario = new ConsultarFuncionario(jdpPrincipal);
        this.jdpPrincipal.add(consultaFuncionario);
        consultaFuncionario.setVisible(true);
    }//GEN-LAST:event_imFuncionarioActionPerformed

    private void imFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imFornecedorActionPerformed
        // TODO add your handling code here:
        ConsultarFornecedor consultaFornecedor = new ConsultarFornecedor(jdpPrincipal);
        this.jdpPrincipal.add(consultaFornecedor);
        consultaFornecedor.setVisible(true);
    }//GEN-LAST:event_imFornecedorActionPerformed

    private void imCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCompraActionPerformed
        // TODO add your handling code here:
        ConsultarCompra consultaCompra = new ConsultarCompra(jdpPrincipal);
        this.jdpPrincipal.add(consultaCompra);
        consultaCompra.setVisible(true);
    }//GEN-LAST:event_imCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu imCadastro;
    private javax.swing.JMenuItem imCargo;
    private javax.swing.JMenuItem imCliente;
    private javax.swing.JMenuItem imCompra;
    private javax.swing.JMenuItem imFornecedor;
    private javax.swing.JMenuItem imFuncionario;
    private javax.swing.JMenuItem imProduto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdpPrincipal;
    // End of variables declaration//GEN-END:variables
}
